export const GENRE_CODE_HASH = [
    {code: "G001", label: "居酒屋"},
    {code: "G002", label: "ダイニングバー・バル"},
    {code: "G003", label: "創作料理"},
    {code: "G004", label: "和食"},
    {code: "G005", label: "洋食"},
    {code: "G006", label: "イタリアン・フレンチ"},
    {code: "G007", label: "中華"},
    {code: "G008", label: "焼肉・ホルモン"},
    {code: "G017", label: "韓国料理"},
    {code: "G009", label: "アジア・エスニック料理"},
    {code: "G010", label: "各国料理"},
    {code: "G011", label: "カラオケ・パーティ"},
    {code: "G012", label: "バー・カクテル"},
    {code: "G013", label: "ラーメン"},
    {code: "G016", label: "お好み焼き・もんじゃ"},
    {code: "G014", label: "カフェ・スイーツ"},
    {code: "G015", label: "その他グルメ"},
]